let shopItemsData = [{
 id:"itema",
 name: "Rust Suit Jacket",
 price: 35,
 img: "/products/rust-relaxed-fit-suit-jacket.jpg",
},
{
id: "itemb",
 name: "Pink Floral Shirt",
 price: 35,
 img: "/products/pink-floral-revere-collar-shirt.jpg",
}, 
{
id: "itemc",
name: "Black Tie Dress",
price: 10,
img: "/products/black-tie-waist-button-front-pleated-hem-mini-shirt-dress.jpg",
},
{
id: "itemd",
name: "Camel Blazer",
price: 20,
img: "/products/camel-long-sleeve-relaxed-fit-blazer.jpg",
},
{
id: "iteme",
name: "Black Denim Jacket",
price: 30,
img: "/products/black-denim-double-pocket-hooded-jacket.jpg",
},
{
id: "itemf",
name: "Black Crew Neck Shirt",
price: 15,
img: "/products/girls-black-crew-neck-acdc-logo-t-shirt.jpg",
},
{
id: "itemg",
name: "Olive Cargo Tousers",
price: 20,
img: "/products/olive-slim-fit-cargo-trousers.jpg",
},
{
id: "itemh",
name: "Grey Leather Trainers",
price: 50,
img: "/products/grey-leather-look-lace-up-trainers.jpg",
},
{
id: "itemi",
name: "Blue Skinny Jeans",
price: 30,
img: "/products/pale-blue-skinny-jeans.jpg",
},
{
id: "itemj",
name: "Burgundy Hoodie",
price: 25,
img: "/products/boys-burgundy-jersey-pocket-front-hoodie.jpg",
},]